### ISSUE TITLE
Show the migration of the data from HBase to MapR-DB Binary

### ISSUE THREAD

**Issue by tgrall** [mapr-demos/hbase-to-maprdb#1]
So far we have the code and documentation explaining how to write the Java app that will be running on MapR-DB

What we should also show, pointing to maprdocs when needed is:
1. the Hbase application with data
2. migrat/move the data from hbase to Mapr-db

So we can have a script that imports data into Hbase

**Comment by mmamadilov** [comment]
Created [document](https://github.com/mapr-demos/hbase-to-maprdb/blob/master/doc/data-migration.md), which shows how to migrate the data from HBase to MapR-DB Binary. Also, created [script](https://github.com/mapr-demos/hbase-to-maprdb/blob/master/bin/init-hbase-test-table.script) for HBase table initialization.
